// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJS3pqhUk3yCB4-yGHNs2Sd6Ys2BwuXEk',
    appId: '1:351536282491:web:b56b6e4b7c59af7e2a1bde',
    messagingSenderId: '351536282491',
    projectId: 'maamedicos2',
    authDomain: 'maamedicos2.firebaseapp.com',
    storageBucket: 'maamedicos2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFl7ead9KQQx12e7Cu6yEUCBj84ff2HA8',
    appId: '1:351536282491:android:153f64492b79f9e62a1bde',
    messagingSenderId: '351536282491',
    projectId: 'maamedicos2',
    storageBucket: 'maamedicos2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2i7OqI1b8vM-0L9Sz2Jvb6UN40_mMzA0',
    appId: '1:351536282491:ios:07f3e87172b6c4262a1bde',
    messagingSenderId: '351536282491',
    projectId: 'maamedicos2',
    storageBucket: 'maamedicos2.firebasestorage.app',
    iosBundleId: 'com.example.maamedicos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2i7OqI1b8vM-0L9Sz2Jvb6UN40_mMzA0',
    appId: '1:351536282491:ios:07f3e87172b6c4262a1bde',
    messagingSenderId: '351536282491',
    projectId: 'maamedicos2',
    storageBucket: 'maamedicos2.firebasestorage.app',
    iosBundleId: 'com.example.maamedicos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJS3pqhUk3yCB4-yGHNs2Sd6Ys2BwuXEk',
    appId: '1:351536282491:web:bc7b19505a86e5cc2a1bde',
    messagingSenderId: '351536282491',
    projectId: 'maamedicos2',
    authDomain: 'maamedicos2.firebaseapp.com',
    storageBucket: 'maamedicos2.firebasestorage.app',
  );

}